const prisma = require('../prisma/client');
const express = require('express');
const router = express.Router();
const auth = require('../middleware/auth');
const PDFDocument = require('pdfkit');
const XLSX = require('xlsx');

// @route   GET /api/intelligence/student
// @desc    Get academic health and insights for the logged-in student
router.get('/student', auth, async (req, res) => {
  try {
    let health = await prisma.academicHealth.findFirst({ where: { studentId: req.user.id } });
    if (!health) {
      health = await prisma.academicHealth.create({ data: {
        studentId: req.user.id,
        healthScore: 85,
        components: { attendanceScore: 90, testScore: 82, assignmentScore: 88, studyActivityScore: 75 },
        status: 'Good'
      } });
    }

    let insight = await prisma.performanceInsight.findFirst({ where: { studentId: req.user.id } });
    if (!insight) {
      insight = await prisma.performanceInsight.create({ data: {
        studentId: req.user.id,
        performanceScore: 82,
        growthScore: 15,
        predictedRank: 12500,
        predictedPercentile: 96.5,
        successProbability: 88,
        readinessLevel: 'Good',
        weeklyGrowth: 2.5,
        monthlyGrowth: 8.4,
        learningConsistencyScore: 92,
        improvementScore: 85,
        aiInsights: [
          'You improved by 8.4% this month.',
          'Your attendance is solid, keep it up!',
          'Physics is your strongest subject, but chemistry needs focus.',
          'Great consistency in completing assignments on time.'
        ]
      } });
    }

    const topics = await prisma.topicAnalytics.findMany({ where: { studentId: req.user.id } });
    const strongTopics = topics.filter(t => t.status === 'Strong').map(t => t.topic);
    const weakTopics = topics.filter(t => t.status === 'Weak' || t.status === 'Critical').map(t => t.topic);

    const subjects = await prisma.subjectAnalytics.findMany({
      where: { studentId: req.user.id },
      orderBy: { averageAccuracy: 'desc' }
    });

    res.json({
      health,
      insight,
      strongTopics,
      weakTopics,
      subjects
    });
  } catch (err) {
    console.error(err.message);
    res.status(500).send('Server Error');
  }
});

// @route   GET /api/intelligence/teacher
// @desc    Get intelligence overview for a teacher's batch
router.get('/teacher', auth, async (req, res) => {
  try {
    const teacher = await prisma.user.findUnique({ where: { id: req.user.id } });
    const students = await prisma.user.findMany({ where: { role: 'Student', 'programInfo.program': teacher.programInfo.program } });
    
    const risks = await prisma.riskPrediction.findMany({
      where: { program: teacher.programInfo.program },
      include: { student: { select: { fullName: true, email: true } } }
    });
  } catch (err) {
    console.error(err.message);
    res.status(500).send('Server Error');
  }
});

// @route   GET /api/intelligence/report
// @desc    Generate and download reports
router.get('/report', auth, async (req, res) => {
  try {
    const { format, type } = req.query; // format: 'pdf' | 'excel', type: 'student' | 'teacher' | 'admin'

    if (format === 'pdf') {
      const doc = new PDFDocument();
      res.setHeader('Content-disposition', `attachment; filename=academic-report-${Date.now()}.pdf`);
      res.setHeader('Content-type', 'application/pdf');
      
      doc.pipe(res);
      doc.fontSize(25).text('Sri Shirdi Sai Institutions', 100, 100);
      doc.fontSize(18).text(`Academic Intelligence Report (${type.toUpperCase()})`, 100, 140);
      doc.fontSize(12).text(`Generated on: ${new Date().toLocaleDateString()}`, 100, 180);
      doc.text('Confidential automated report generated by the AI Analytics Engine.', 100, 220);
      doc.end();
    } else if (format === 'excel') {
      const wb = XLSX.utils.book_new();
      const ws_data = [
        ["Report Type", "Generated On", "Status"],
        [type.toUpperCase(), new Date().toLocaleDateString(), "Generated via AI Engine"]
      ];
      const ws = XLSX.utils.aoa_to_sheet(ws_data);
      XLSX.utils.book_append_sheet(wb, ws, "Report");
      
      const buffer = XLSX.write(wb, { type: 'buffer', bookType: 'xlsx' });
      
      res.setHeader('Content-disposition', `attachment; filename=academic-report-${Date.now()}.xlsx`);
      res.setHeader('Content-type', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
      res.send(buffer);
    } else {
      res.status(400).json({ msg: 'Invalid format requested' });
    }
  } catch (err) {
    console.error(err.message);
    res.status(500).send('Server Error');
  }
});

module.exports = router;
