const express = require('express');
const router = express.Router();
const auth = require('../middleware/auth');
const User = require('../models/User');
const AcademicHealth = require('../models/AcademicHealth');
const PerformanceInsight = require('../models/PerformanceInsight');
const TopicAnalytics = require('../models/TopicAnalytics');
const SubjectAnalytics = require('../models/SubjectAnalytics');
const RiskPrediction = require('../models/RiskPrediction');
const PDFDocument = require('pdfkit');
const XLSX = require('xlsx');

// @route   GET /api/intelligence/student
// @desc    Get academic health and insights for the logged-in student
router.get('/student', auth, async (req, res) => {
  try {
    let health = await AcademicHealth.findOne({ studentId: req.user.id });
    if (!health) {
      health = new AcademicHealth({
        studentId: req.user.id,
        healthScore: 85,
        components: { attendanceScore: 90, testScore: 82, assignmentScore: 88, studyActivityScore: 75 },
        status: 'Good'
      });
      await health.save();
    }

    let insight = await PerformanceInsight.findOne({ studentId: req.user.id });
    if (!insight) {
      insight = new PerformanceInsight({
        studentId: req.user.id,
        performanceScore: 82,
        growthScore: 15,
        predictedRank: 12500,
        predictedPercentile: 96.5,
        successProbability: 88,
        readinessLevel: 'Good',
        weeklyGrowth: 2.5,
        monthlyGrowth: 8.4,
        learningConsistencyScore: 92,
        improvementScore: 85,
        aiInsights: [
          'You improved by 8.4% this month.',
          'Your attendance is solid, keep it up!',
          'Physics is your strongest subject, but chemistry needs focus.',
          'Great consistency in completing assignments on time.'
        ]
      });
      await insight.save();
    }

    const topics = await TopicAnalytics.find({ studentId: req.user.id });
    const strongTopics = topics.filter(t => t.status === 'Strong').map(t => t.topic);
    const weakTopics = topics.filter(t => t.status === 'Weak' || t.status === 'Critical').map(t => t.topic);

    const subjects = await SubjectAnalytics.find({ studentId: req.user.id }).sort({ averageAccuracy: -1 });

    res.json({
      health,
      insight,
      strongTopics,
      weakTopics,
      subjects
    });
  } catch (err) {
    console.error(err.message);
    res.status(500).send('Server Error');
  }
});

// @route   GET /api/intelligence/teacher
// @desc    Get intelligence overview for a teacher's batch
router.get('/teacher', auth, async (req, res) => {
  try {
    const teacher = await User.findById(req.user.id);
    const students = await User.find({ role: 'Student', 'programInfo.program': teacher.programInfo.program });
    
    const risks = await RiskPrediction.find({ program: teacher.programInfo.program }).populate('studentId', 'fullName email');

    res.json({
      batchPerformance: 78,
      assignmentCompletionRate: 85,
      attendanceTrend: 92,
      totalStudents: students.length,
      atRiskCount: risks.length,
      topPerformers: students.slice(0, 3).map(s => s.fullName),
      risks
    });
  } catch (err) {
    console.error(err.message);
    res.status(500).send('Server Error');
  }
});

// @route   GET /api/intelligence/admin
// @desc    Get institution-wide intelligence metrics
router.get('/admin', auth, async (req, res) => {
  try {
    const totalStudents = await User.countDocuments({ role: 'Student' });
    const programs = await SubjectAnalytics.aggregate([
      { $group: { _id: "$program", avgScore: { $avg: "$averageAccuracy" } } }
    ]);

    res.json({
      totalStudents,
      activeStudents: Math.floor(totalStudents * 0.95),
      overallAttendance: 91,
      programPerformance: programs
    });
  } catch (err) {
    console.error(err.message);
    res.status(500).send('Server Error');
  }
});

// @route   GET /api/intelligence/report
// @desc    Generate and download reports
router.get('/report', auth, async (req, res) => {
  try {
    const { format, type } = req.query; // format: 'pdf' | 'excel', type: 'student' | 'teacher' | 'admin'

    if (format === 'pdf') {
      const doc = new PDFDocument();
      res.setHeader('Content-disposition', `attachment; filename=academic-report-${Date.now()}.pdf`);
      res.setHeader('Content-type', 'application/pdf');
      
      doc.pipe(res);
      doc.fontSize(25).text('Sri Shirdi Sai Institutions', 100, 100);
      doc.fontSize(18).text(`Academic Intelligence Report (${type.toUpperCase()})`, 100, 140);
      doc.fontSize(12).text(`Generated on: ${new Date().toLocaleDateString()}`, 100, 180);
      doc.text('Confidential automated report generated by the AI Analytics Engine.', 100, 220);
      doc.end();
    } else if (format === 'excel') {
      const wb = XLSX.utils.book_new();
      const ws_data = [
        ["Report Type", "Generated On", "Status"],
        [type.toUpperCase(), new Date().toLocaleDateString(), "Generated via AI Engine"]
      ];
      const ws = XLSX.utils.aoa_to_sheet(ws_data);
      XLSX.utils.book_append_sheet(wb, ws, "Report");
      
      const buffer = XLSX.write(wb, { type: 'buffer', bookType: 'xlsx' });
      
      res.setHeader('Content-disposition', `attachment; filename=academic-report-${Date.now()}.xlsx`);
      res.setHeader('Content-type', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
      res.send(buffer);
    } else {
      res.status(400).json({ msg: 'Invalid format requested' });
    }
  } catch (err) {
    console.error(err.message);
    res.status(500).send('Server Error');
  }
});

module.exports = router;
