const prisma = require('./prisma/client');
const bcrypt = require('bcryptjs');

const programs = [
  { name: 'IIT', stream: 'MPC', exams: ['JEE'] },
  { name: 'NEET', stream: 'BiPC', exams: ['NEET'] },
  { name: 'UPSC', stream: 'MEC', exams: ['UPSC'] }
];

const firstNames = ['Aarav', 'Vivaan', 'Aditya', 'Vihaan', 'Arjun', 'Sai', 'Ayaan', 'Krishna', 'Ishaan', 'Shaurya', 'Ananya', 'Diya', 'Avni', 'Aadya', 'Kiara', 'Navya', 'Myra', 'Prisha', 'Riya', 'Sara', 'Kabir', 'Rohan', 'Sneha', 'Rahul', 'Nisha'];
const lastNames = ['Reddy', 'Sharma', 'Patel', 'Kumar', 'Singh', 'Rao', 'Verma', 'Gupta', 'Nair', 'Menon', 'Joshi', 'Choudhury', 'Iyer', 'Desai'];

function getRandomName() {
  const f = firstNames[Math.floor(Math.random() * firstNames.length)];
  const l = lastNames[Math.floor(Math.random() * lastNames.length)];
  return `${f} ${l}`;
}

const seedPilotData = async () => {
  try {
    const salt = await bcrypt.genSalt(10);
    const hashedPassword = await bcrypt.hash('password123', salt);

    console.log('--- CLEARING OLD MOCK DATA ---');
    // Clear old users generated by scripts (emails starting with user or mockstudent)
    await prisma.user.deleteMany({
      where: {
        OR: [
          { email: { startsWith: 'user' } },
          { email: { startsWith: 'mockstudent' } }
        ]
      }
    });

    console.log('--- GENERATING TEACHERS ---');
    const teachers = {};
    for (const p of programs) {
      const email = `teacher.${p.name.toLowerCase()}@pilot.com`;
      let teacher = await prisma.user.findFirst({ where: { email } });
      if (!teacher) {
        teacher = await prisma.user.create({
          data: {
            fullName: `Dr. ${getRandomName()} (Faculty)`,
            email,
            password: hashedPassword,
            mobileNumber: `987654321${Math.floor(Math.random() * 9)}`,
            role: 'Teacher',
            assignedProgram: p.name,
            isApproved: true
          }
        });
      }
      teachers[p.name] = teacher;
    }

    console.log('--- GENERATING STUDENTS ---');
    let allStudents = [];
    for (const p of programs) {
      console.log(`Generating 15 students for ${p.name}...`);
      for (let i = 1; i <= 15; i++) {
        const email = `mockstudent_${p.name.toLowerCase()}_${i}@pilot.com`;
        let student = await prisma.user.create({
          data: {
            fullName: getRandomName(),
            email: email,
            password: hashedPassword,
            mobileNumber: `98${Math.floor(10000000 + Math.random() * 90000000)}`,
            role: 'Student',
            programInfo_program: p.name,
            programInfo_stream: p.stream,
            programInfo_exams: p.exams,
            isApproved: true,
            status: 'Active'
          }
        });
        allStudents.push(student);

        // Attendance (14 days)
        let presentCount = 0;
        for (let d = 0; d < 14; d++) {
          const date = new Date();
          date.setDate(date.getDate() - d);
          date.setHours(0, 0, 0, 0);
          const isPresent = Math.random() > 0.15; // 85% attendance
          if (isPresent) presentCount++;
          await prisma.attendance.create({
            data: { studentId: student.id, date, status: isPresent ? 'Present' : 'Absent' }
          });
        }
        const attendanceScore = (presentCount / 14) * 100;

        // Tests & Results
        let test = await prisma.test.findFirst({ where: { title: `${p.name} Pilot Mock Test` } });
        if (!test) {
          test = await prisma.test.create({
            data: {
              title: `${p.name} Pilot Mock Test`,
              program: p.name,
              stream: p.stream,
              subject: 'Combined',
              totalMarks: p.name === 'IIT' ? 300 : (p.name === 'NEET' ? 720 : 100),
              durationMinutes: 180,
              startDate: new Date(),
              questions: []
            }
          });
        }
        
        let maxMarks = test.totalMarks;
        let score = Math.floor(maxMarks * (0.3 + Math.random() * 0.6)); // 30-90%
        await prisma.testResult.create({
          data: {
            studentId: student.id,
            testId: test.id,
            score: score,
            rank: Math.floor(Math.random() * 50) + 1,
            weakAreas: ['Time Management', 'Tricky Logic'],
            strongAreas: ['Direct Memory', 'Formulas']
          }
        });
        const testScoreNormalized = (score / maxMarks) * 100;

        // Assignments
        let assignment = await prisma.assignment.findFirst({ where: { title: `${p.name} Weekend Assignment` } });
        if (!assignment) {
          assignment = await prisma.assignment.create({
            data: {
              title: `${p.name} Weekend Assignment`,
              program: p.name,
              stream: p.stream,
              subject: p.name === 'IIT' ? 'Physics' : (p.name === 'NEET' ? 'Biology' : 'History'),
              dueDate: new Date(new Date().getTime() + 2 * 24 * 60 * 60 * 1000),
              maxMarks: 50,
              teacherId: teachers[p.name].id,
              status: 'Active'
            }
          });
        }

        const assignmentScore = Math.floor(30 + Math.random() * 20); // 30-50 marks out of 50
        await prisma.assignmentSubmission.create({
          data: {
            assignmentId: assignment.id,
            studentId: student.id,
            submissionDate: new Date(),
            status: 'Graded',
            marksAwarded: assignmentScore
          }
        });
        const assignmentScoreNormalized = (assignmentScore / 50) * 100;

        // Academic Health
        const studyScore = Math.floor(50 + Math.random() * 50);
        const healthScore = Math.floor((attendanceScore * 0.2) + (testScoreNormalized * 0.5) + (assignmentScoreNormalized * 0.2) + (studyScore * 0.1));
        let status = 'Average';
        if (healthScore > 85) status = 'Excellent';
        else if (healthScore > 70) status = 'Good';
        else if (healthScore < 50) status = 'Critical';
        else if (healthScore < 65) status = 'Needs Improvement';

        await prisma.academicHealth.create({
          data: {
            studentId: student.id,
            healthScore,
            components_attendanceScore: attendanceScore,
            components_testScore: testScoreNormalized,
            components_assignmentScore: assignmentScoreNormalized,
            components_studyActivityScore: studyScore,
            status
          }
        });

        // Performance Insights
        await prisma.performanceInsight.create({
          data: {
            studentId: student.id,
            performanceScore: healthScore,
            growthScore: Math.floor(Math.random() * 20),
            aiInsights: [
              "Student shows consistent growth in weekly tests.",
              "Needs to focus on theoretical concepts to avoid negative marking.",
              "Attendance is stable, but homework completion time can improve."
            ],
            readinessLevel: healthScore > 75 ? 'High' : 'Moderate'
          }
        });

        // Ranking
        await prisma.ranking.create({
          data: {
            studentId: student.id,
            program: p.name,
            overallScore: healthScore,
            attendanceScore,
            assignmentScore: assignmentScoreNormalized,
            testScore: testScoreNormalized,
            healthScore
          }
        });

        // Mock Interviews (for a few students)
        if (Math.random() > 0.5) {
          await prisma.mockInterview.create({
            data: {
              studentId: student.id,
              interviewType: 'Concept Clearance',
              durationMinutes: 15,
              feedback_communicationScore: Math.floor(6 + Math.random() * 4),
              feedback_confidenceScore: Math.floor(6 + Math.random() * 4),
              feedback_knowledgeScore: Math.floor(6 + Math.random() * 4),
              feedback_overallRemarks: "Good understanding but hesitated on application questions.",
              date: new Date()
            }
          });
        }

        // Behavior Feedback
        if (Math.random() > 0.6) {
          await prisma.behaviorFeedback.create({
            data: {
              teacher: teachers[p.name].id,
              student: student.id,
              rating: (Math.floor(3 + Math.random() * 2)).toString(), // 3-5 rating
              comments: "Very attentive in class today. Asked good doubts.",
              createdAt: new Date()
            }
          });
        }

        // Messages
        if (Math.random() > 0.7) {
          await prisma.message.create({
            data: {
              sender: student.id,
              receiver: teachers[p.name].id,
              content: `Hello sir, I have a doubt in today's ${p.name} class assignment.`,
              read: false,
              timestamp: new Date()
            }
          });
          
          await prisma.message.create({
            data: {
              sender: teachers[p.name].id,
              receiver: student.id,
              content: `Yes, tell me. I will explain the logic right now.`,
              read: true,
              timestamp: new Date()
            }
          });
        }
      } // end 15 students loop
    } // end programs loop

    console.log('--- RECALCULATING RANKS ---');
    const allRanks = await prisma.ranking.findMany({ orderBy: { overallScore: 'desc' } });
    let globalRankCounter = 1;
    for (let r of allRanks) {
      await prisma.ranking.update({
        where: { id: r.id },
        data: { globalRank: globalRankCounter++ }
      });
    }

    for (const p of programs) {
      const progRanks = await prisma.ranking.findMany({ where: { program: p.name }, orderBy: { overallScore: 'desc' } });
      let progRankCounter = 1;
      for (let r of progRanks) {
        await prisma.ranking.update({
          where: { id: r.id },
          data: { programRank: progRankCounter++ }
        });
      }
    }

    console.log('--- GENERATING MATERIALS & ANNOUNCEMENTS ---');
    for (const p of programs) {
      let materialTitle = `${p.name} Advanced Pilot Study Material`;
      let m = await prisma.material.findFirst({ where: { title: materialTitle } });
      if (!m) {
        await prisma.material.create({
          data: {
            title: materialTitle,
            type: 'PDF',
            program: p.name,
            stream: p.stream,
            subject: 'General',
            url: 'https://example.com/pilot_material.pdf',
            uploadedAt: new Date()
          }
        });
      }

      let annTitle = `${p.name} Pilot Launch Announcement`;
      let a = await prisma.announcement.findFirst({ where: { title: annTitle } });
      if (!a) {
        await prisma.announcement.create({
          data: {
            title: annTitle,
            content: `Welcome to the ${p.name} Pilot phase. All modules are live.`,
            targetProgram: p.name,
            priority: 'High',
            date: new Date()
          }
        });
      }
    }

    console.log('Successfully generated complete pilot-ready mock data!');
    process.exit(0);
  } catch (err) {
    console.error(err);
    process.exit(1);
  }
};

seedPilotData();
